// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fast_glm_fit
List fast_glm_fit(const arma::mat& X, const arma::vec& y, const std::string& family, int max_iter, double tol);
RcppExport SEXP _causalreg_fast_glm_fit(SEXP XSEXP, SEXP ySEXP, SEXP familySEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_glm_fit(X, y, family, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}
// pearson_stat_cpp
double pearson_stat_cpp(const arma::vec& y, const arma::vec& mu, const std::string& family);
RcppExport SEXP _causalreg_pearson_stat_cpp(SEXP ySEXP, SEXP muSEXP, SEXP familySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    rcpp_result_gen = Rcpp::wrap(pearson_stat_cpp(y, mu, family));
    return rcpp_result_gen;
END_RCPP
}
// glm_loglik_cpp
double glm_loglik_cpp(const arma::vec& y, const arma::vec& mu, const std::string& family);
RcppExport SEXP _causalreg_glm_loglik_cpp(SEXP ySEXP, SEXP muSEXP, SEXP familySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    rcpp_result_gen = Rcpp::wrap(glm_loglik_cpp(y, mu, family));
    return rcpp_result_gen;
END_RCPP
}
// fast_glm_bic
double fast_glm_bic(const arma::vec& y, const arma::vec& mu, const std::string& family, int p, int n);
RcppExport SEXP _causalreg_fast_glm_bic(SEXP ySEXP, SEXP muSEXP, SEXP familySEXP, SEXP pSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_glm_bic(y, mu, family, p, n));
    return rcpp_result_gen;
END_RCPP
}
// fast_fit_and_stat
List fast_fit_and_stat(const arma::mat& X, const arma::vec& y, const std::string& family);
RcppExport SEXP _causalreg_fast_fit_and_stat(SEXP XSEXP, SEXP ySEXP, SEXP familySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    rcpp_result_gen = Rcpp::wrap(fast_fit_and_stat(X, y, family));
    return rcpp_result_gen;
END_RCPP
}
// boot_pval_cpp
double boot_pval_cpp(const arma::mat& X, const arma::vec& y, const std::string& family, int B);
RcppExport SEXP _causalreg_boot_pval_cpp(SEXP XSEXP, SEXP ySEXP, SEXP familySEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(boot_pval_cpp(X, y, family, B));
    return rcpp_result_gen;
END_RCPP
}
// eval_submodels_cpp
List eval_submodels_cpp(const arma::mat& X_full, const arma::vec& y, const std::string& family, const List& col_indices, const std::string& pval_method, int B);
RcppExport SEXP _causalreg_eval_submodels_cpp(SEXP X_fullSEXP, SEXP ySEXP, SEXP familySEXP, SEXP col_indicesSEXP, SEXP pval_methodSEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X_full(X_fullSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const List& >::type col_indices(col_indicesSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type pval_method(pval_methodSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(eval_submodels_cpp(X_full, y, family, col_indices, pval_method, B));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_causalreg_fast_glm_fit", (DL_FUNC) &_causalreg_fast_glm_fit, 5},
    {"_causalreg_pearson_stat_cpp", (DL_FUNC) &_causalreg_pearson_stat_cpp, 3},
    {"_causalreg_glm_loglik_cpp", (DL_FUNC) &_causalreg_glm_loglik_cpp, 3},
    {"_causalreg_fast_glm_bic", (DL_FUNC) &_causalreg_fast_glm_bic, 5},
    {"_causalreg_fast_fit_and_stat", (DL_FUNC) &_causalreg_fast_fit_and_stat, 3},
    {"_causalreg_boot_pval_cpp", (DL_FUNC) &_causalreg_boot_pval_cpp, 4},
    {"_causalreg_eval_submodels_cpp", (DL_FUNC) &_causalreg_eval_submodels_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_causalreg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
