# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fast GLM fit via IRLS
#'
#' @param X Design matrix (n x p), including intercept column if needed
#' @param y Response vector (n)
#' @param family "poisson" or "binomial"
#' @param max_iter Maximum IRLS iterations (default 25)
#' @param tol Convergence tolerance (default 1e-8)
#' @return List with fitted_values (mu) and converged flag
fast_glm_fit <- function(X, y, family, max_iter = 25L, tol = 1e-8) {
    .Call(`_causalreg_fast_glm_fit`, X, y, family, max_iter, tol)
}

#' Compute Pearson chi-square statistic from y and mu
#'
#' @param y Response vector
#' @param mu Fitted values
#' @param family "poisson" or "binomial"
#' @return Pearson chi-square statistic (sum of squared Pearson residuals)
pearson_stat_cpp <- function(y, mu, family) {
    .Call(`_causalreg_pearson_stat_cpp`, y, mu, family)
}

#' Compute log-likelihood for Poisson or Binomial GLM
#'
#' @param y Response vector
#' @param mu Fitted values
#' @param family "poisson" or "binomial"
#' @return Log-likelihood value
glm_loglik_cpp <- function(y, mu, family) {
    .Call(`_causalreg_glm_loglik_cpp`, y, mu, family)
}

#' Compute BIC for a GLM fit
#'
#' @param y Response vector
#' @param mu Fitted values
#' @param family "poisson" or "binomial"
#' @param p Number of parameters
#' @param n Number of observations
#' @return BIC value
fast_glm_bic <- function(y, mu, family, p, n) {
    .Call(`_causalreg_fast_glm_bic`, y, mu, family, p, n)
}

#' Fit GLM and compute Pearson risk, BIC, and optionally bootstrap p-value
#'
#' @param X Design matrix
#' @param y Response vector
#' @param family "poisson" or "binomial"
#' @return List with pearson_stat, pearson_risk, bic
fast_fit_and_stat <- function(X, y, family) {
    .Call(`_causalreg_fast_fit_and_stat`, X, y, family)
}

#' Bootstrap p-value for Pearson risk = 1 test (fully in C++)
#'
#' @param X Design matrix
#' @param y Response vector
#' @param family "poisson" or "binomial"
#' @param B Number of bootstrap replicates
#' @return Two-sided bootstrap p-value
boot_pval_cpp <- function(X, y, family, B = 100L) {
    .Call(`_causalreg_boot_pval_cpp`, X, y, family, B)
}

#' Evaluate multiple submodels in C++ (for exhaustive search)
#'
#' Given a full design matrix and a list of column index vectors,
#' fit each submodel and return Pearson risk, p-value, BIC.
#'
#' @param X_full Full design matrix (with intercept)
#' @param y Response vector
#' @param family "poisson" or "binomial"
#' @param col_indices List of integer vectors, each specifying columns of X_full
#' @param pval_method "chi-square" or "bootstrap"
#' @param B Number of bootstrap replicates
#' @return List of vectors: pearson_risk, pval, bic
eval_submodels_cpp <- function(X_full, y, family, col_indices, pval_method, B = 100L) {
    .Call(`_causalreg_eval_submodels_cpp`, X_full, y, family, col_indices, pval_method, B)
}

